#!/usr/bin/env python3
"""Generate per-(dataset, model) pipeline configs for the remote vastai matrix.

Produces 88 yamls (4 datasets x 22 models = 11 base + 11 fine-tuned) under
configs-remote/<dataset>/. Each yaml runs a SINGLE model invocation suitable
for the per-combo tmux session scheme.

Paths assume the vastai layout:
  /workspace/data/<dataset>.csv
  /workspace/ft-models/<family>/<name>-all-data/final
  /workspace/gec-results/<run-tag>/<dataset>/<model>

Usage:
    python scripts/gen_remote_configs.py --run-tag eval-gec-errant-2026-05-04
"""
import argparse
import sys
from pathlib import Path

# (name, hf_id_or_path, family, gen_batch_size)
# gen_batch_size tuned for 32 GB GPU; same heuristics as configs/pipeline/celva-all-models.yaml
BASE_MODELS = [
    ("gpt2-small",   "gpt2",                          "gpt2",    1024),
    ("gpt2-medium",  "gpt2-medium",                   "gpt2",     512),
    ("gpt2-large",   "gpt2-large",                    "gpt2",     192),
    ("pythia-70m",   "EleutherAI/pythia-70m",         "pythia",  1024),
    ("pythia-160m",  "EleutherAI/pythia-160m",        "pythia",  1024),
    ("pythia-410m",  "EleutherAI/pythia-410m",        "pythia",   512),
    ("pythia-1b",    "EleutherAI/pythia-1b",          "pythia",   256),
    ("pythia-1.4b",  "EleutherAI/pythia-1.4b",        "pythia",   192),
    ("smollm2-135m", "HuggingFaceTB/SmolLM2-135M",    "smollm2", 1024),
    ("smollm2-360m", "HuggingFaceTB/SmolLM2-360M",    "smollm2",  512),
    ("smollm2-1.7b", "HuggingFaceTB/SmolLM2-1.7B",    "smollm2",  192),
]

# ft variants point at /workspace/ft-models/<family>/<name>-all-data/final
# (matching the gdrive layout under i:/_p/artificial-learners/models/)
FT_MODELS = [
    (f"ft-{name}", f"/workspace/ft-models/{family}/{name}-all-data/final",
     family, batch)
    for (name, _hf, family, batch) in BASE_MODELS
]

DATASETS = [
    # (slug, remote_csv_path)
    ("efcamdat-test", "/workspace/data/norm-EFCAMDAT-test.csv"),
    ("celva-sp",      "/workspace/data/norm-CELVA-SP.csv"),
    ("kupa-keys",     "/workspace/data/norm-KUPA-KEYS.csv"),
    ("fce",           "/workspace/data/norm-FCE.csv"),
]

CONFIG_TEMPLATE = """\
# Auto-generated by scripts/gen_remote_configs.py — do not hand-edit.
# Dataset: {dataset}
# Model:   {model_name} ({kind})
# Run-tag: {run_tag}
data_loader:
  data_path: {data_path}
  text_column: text
  max_sentences: {max_sentences}
  min_words: 10
  max_words: 500
  prompt_ratio: 0.5
  min_prompt_words: 5
  split_sentences: true

generation:
  max_new_tokens: 50
  min_new_tokens: 10
  temperature: 1.0
  top_k: 50
  top_p: 0.95
  do_sample: true
  repetition_penalty: 1.2

gec:
  method: dedicated
  model_id: grammarly/coedit-large
  batch_size: 64
  device: auto

annotation:
  lang: en

analysis:
  skip_plots: false
  top_n_error_types: 10

models:
  - name: {model_name}
    hf_model_id: {hf_id}
    model_family: {family}
    {is_learner_tuned_line}batch_size: {gen_batch}

batch_size: 32
device: auto
seed: 42
output_dir: /workspace/gec-results/{run_tag}/{dataset}/{model_name}
skip_plots: false
include_learner_baseline: true
"""


def write_one(out_root: Path, dataset: str, data_path: str, run_tag: str,
              model_name: str, hf_id: str, family: str, gen_batch: int,
              is_ft: bool, max_sentences: str) -> Path:
    kind = "fine-tuned" if is_ft else "base"
    is_lt = "is_learner_tuned: true\n    " if is_ft else ""
    out_dir = out_root / dataset
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{dataset}-{model_name}.yaml"
    out_path.write_text(CONFIG_TEMPLATE.format(
        dataset=dataset,
        model_name=model_name,
        kind=kind,
        run_tag=run_tag,
        data_path=data_path,
        max_sentences=max_sentences,
        hf_id=hf_id,
        family=family,
        is_learner_tuned_line=is_lt,
        gen_batch=gen_batch,
    ))
    return out_path


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--run-tag", default="eval-gec-errant-2026-05-04")
    p.add_argument("--out-root", type=Path,
                   default=Path(__file__).resolve().parents[1] / "configs-remote")
    p.add_argument("--max-sentences", default="null",
                   help="'null' for full dataset, or an int for capping")
    args = p.parse_args()

    n = 0
    for ds_slug, ds_path in DATASETS:
        for spec, is_ft in [(BASE_MODELS, False), (FT_MODELS, True)]:
            for (model_name, hf_id, family, gen_batch) in spec:
                out = write_one(
                    args.out_root, ds_slug, ds_path, args.run_tag,
                    model_name, hf_id, family, gen_batch,
                    is_ft, args.max_sentences,
                )
                n += 1
                print(out, file=sys.stderr)
    print(f"wrote {n} configs under {args.out_root}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
